# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: load_balancer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import chat_pb2 as chat__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='load_balancer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13load_balancer.proto\x1a\nchat.proto\"%\n\x04Pong\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.ConnectionInfo\"K\n\x04Load\x12\x0f\n\x07\x63puLoad\x18\x01 \x01(\x02\x12\x13\n\x0bnetworkLoad\x18\x02 \x01(\x02\x12\x1d\n\x04info\x18\x03 \x01(\x0b\x32\x0f.ConnectionInfo\"%\n\x06Status\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.StatusCode\">\n\x07Request\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.RequestType\x12\x17\n\x06thread\x18\x02 \x01(\x0b\x32\x07.Thread\"*\n\x0e\x43onnectionInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t*$\n\nStatusCode\x12\t\n\x05\x45RROR\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01*3\n\x0bRequestType\x12\x10\n\x0c\x43REATETHREAD\x10\x00\x12\x08\n\x04LOAD\x10\x01\x12\x08\n\x04PING\x10\x02\x32\xb0\x01\n\x12LoadBalancerServer\x12\x30\n\x0freceiveRequests\x12\x0f.ConnectionInfo\x1a\x08.Request\"\x00\x30\x01\x12\x1c\n\x08sendLoad\x12\x05.Load\x1a\x07.Status\"\x00\x12\x1c\n\x08sendPong\x12\x05.Pong\x1a\x07.Status\"\x00\x12,\n\x0e\x43onnectRequest\x12\x07.Thread\x1a\x0f.ConnectionInfo\"\x00\x62\x06proto3')
  ,
  dependencies=[chat__pb2.DESCRIPTOR,])

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=298,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATETHREAD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=336,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
ERROR = 0
SUCCESS = 1
CREATETHREAD = 0
LOAD = 1
PING = 2



_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='Pong.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_LOAD = _descriptor.Descriptor(
  name='Load',
  full_name='Load',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuLoad', full_name='Load.cpuLoad', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='networkLoad', full_name='Load.networkLoad', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='Load.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=149,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Status.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=188,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread', full_name='Request.thread', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=252,
)


_CONNECTIONINFO = _descriptor.Descriptor(
  name='ConnectionInfo',
  full_name='ConnectionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ConnectionInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ConnectionInfo.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=296,
)

_PONG.fields_by_name['info'].message_type = _CONNECTIONINFO
_LOAD.fields_by_name['info'].message_type = _CONNECTIONINFO
_STATUS.fields_by_name['status'].enum_type = _STATUSCODE
_REQUEST.fields_by_name['type'].enum_type = _REQUESTTYPE
_REQUEST.fields_by_name['thread'].message_type = chat__pb2._THREAD
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['Load'] = _LOAD
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['ConnectionInfo'] = _CONNECTIONINFO
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

Load = _reflection.GeneratedProtocolMessageType('Load', (_message.Message,), {
  'DESCRIPTOR' : _LOAD,
  '__module__' : 'load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:Load)
  })
_sym_db.RegisterMessage(Load)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

ConnectionInfo = _reflection.GeneratedProtocolMessageType('ConnectionInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONINFO,
  '__module__' : 'load_balancer_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionInfo)
  })
_sym_db.RegisterMessage(ConnectionInfo)



_LOADBALANCERSERVER = _descriptor.ServiceDescriptor(
  name='LoadBalancerServer',
  full_name='LoadBalancerServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=390,
  serialized_end=566,
  methods=[
  _descriptor.MethodDescriptor(
    name='receiveRequests',
    full_name='LoadBalancerServer.receiveRequests',
    index=0,
    containing_service=None,
    input_type=_CONNECTIONINFO,
    output_type=_REQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendLoad',
    full_name='LoadBalancerServer.sendLoad',
    index=1,
    containing_service=None,
    input_type=_LOAD,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendPong',
    full_name='LoadBalancerServer.sendPong',
    index=2,
    containing_service=None,
    input_type=_PONG,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectRequest',
    full_name='LoadBalancerServer.ConnectRequest',
    index=3,
    containing_service=None,
    input_type=chat__pb2._THREAD,
    output_type=_CONNECTIONINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADBALANCERSERVER)

DESCRIPTOR.services_by_name['LoadBalancerServer'] = _LOADBALANCERSERVER

# @@protoc_insertion_point(module_scope)
